### ISSUE TITLE
wrong documentation

### ISSUE THREAD

**Issue by uncletoxa** [agoloborodko/reposnap#1]
> Alternatively, you can clone the repository and install the required dependencies:
> 
> git clone https://github.com/username/reposnap.git
> cd reposnap
> pip install -r requirements.txt
that won't work because there is no requirements.txt file

**Comment by agoloborodko** [comment]
PR: https://github.com/agoloborodko/reposnap/pull/3

**Comment by agoloborodko** [comment]
Thank you @uncletoxa :)
